[tool.poetry]
name = "kernel"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
flint = { path = "../common-lib/flint", develop = false }
ipykernel = "^6.29.5"
nbformat = "^5.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
