x-storage-creds: &storage-creds
  environment:
    STORAGE_USER: ${STORAGE_USER:-admin}
    STORAGE_PASSWORD: ${STORAGE_PASSWORD:-password}

services:

  # --- BACKEND SERVICES ---

  storage:
    <<: *storage-creds
    image: flintml/storage:0.1.23
    volumes:
      - storage_data:/usr/src/app/localData
      - storage_meta:/usr/src/app/localMetadata
    restart: always

  compute-manager:
    <<: *storage-creds
    image: flintml/compute-manager:0.1.23
    volumes:
      - ${DRIVER_CONFIG}:/app/worker/worker.yaml
      - ${DOCKER_SOCKET:-/dev/null}:/var/run/docker.sock
    restart: always

  experiment-server:
    <<: *storage-creds
    image: flintml/experiment-server:0.1.23
    depends_on:
      storage:
        condition: service_healthy
    volumes:
      - experiment_data:/repo
    restart: always

  ### --- FRONTEND SERVICES ---

  catalog-explorer:
    <<: *storage-creds
    image: flintml/catalog-explorer:0.1.23
    depends_on:
      storage:
        condition: service_healthy
    restart: always

  experiment-tracker:
    image: flintml/experiment-tracker:0.1.23
    depends_on:
      experiment-server:
        condition: service_healthy
    volumes:
      - experiment_data:/repo
    restart: always

  workspace:
    <<: *storage-creds
    image: flintml/workspace:0.1.23
    depends_on:
      - catalog-explorer
      - experiment-tracker
    restart: always

  reverse-proxy:
    image: flintml/reverse-proxy:0.1.23
    depends_on:
      - storage
      - workspace
      - compute-manager
      - catalog-explorer
      - experiment-server
      - experiment-tracker
    ports:
      - "${FLINT_PORT:-8701}:80"
    restart: always

volumes:
  storage_data:
  storage_meta:
  experiment_data: