x-storage-creds: &storage-creds
  environment:
    STORAGE_USER: ${STORAGE_USER:-admin}
    STORAGE_PASSWORD: ${STORAGE_PASSWORD:-password}

services:

  # --- BACKEND SERVICES ---

  storage:
    <<: *storage-creds
    build: ./storage
    volumes:
      - storage_data:/usr/src/app/localData
      - storage_meta:/usr/src/app/localMetadata
    restart: always

  compute-manager:
    <<: *storage-creds
    build: ./compute-manager
    volumes:
      - ${DRIVER_CONFIG}:/app/worker/worker.yaml
      - ${DOCKER_SOCKET:-/dev/null}:/var/run/docker.sock
    restart: always

  experiment-server:
    <<: *storage-creds
    build: 
      context: .
      dockerfile: ./experiment-server/Dockerfile
    depends_on:
      storage:
        condition: service_healthy
    volumes:
      - experiment_data:/repo
    restart: always

  ### --- FRONTEND SERVICES ---

  catalog-explorer:
    <<: *storage-creds
    build: 
      context: .
      dockerfile: ./catalog-explorer/Dockerfile
    depends_on:
      storage:
        condition: service_healthy
    restart: always
    
  experiment-tracker:
    build: ./experiment-tracker
    depends_on:
      experiment-server:
        condition: service_healthy
    volumes:
      - experiment_data:/repo
    restart: always

  workspace:
    <<: *storage-creds
    build: 
      context: .
      dockerfile: ./workspace/Dockerfile
    depends_on:
      - catalog-explorer
      - experiment-tracker
    volumes:
      - workspace_data:/srv/workspace
    restart: always

  reverse-proxy:
    build: ./reverse-proxy
    depends_on:
      storage:
        condition: service_started
      workspace:
        condition: service_started
      compute-manager:
        condition: service_started
      experiment-server:
        condition: service_started
      catalog-explorer:
        condition: service_started
      experiment-tracker:
        condition: service_started
    ports:
      - "${FLINT_PORT:-8701}:80"
    restart: always

volumes:
  storage_data:
  storage_meta:
  experiment_data:
  workspace_data: